Update GeoApiContext.java - Exception using GAE
Fixed GeoApiContext class, because of exception NoClassDefFoundError when using GAE(due of Builder initializing OkHttpRequestHandler). Created another constructor that receives RequestHandler.Builder as workaround.